apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx
        envirnment: dev-web
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.1
        ports:
          - containerPort: 80
